config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root to: "campaigns#home"
  get 'dashboard', to: 'campaigns#dashboard'
  get 'pricing', to: 'pages#pricing'
  get 'terms', to: 'pages#terms'
  get 'stripe_accounts/full', to: 'stripe_accounts#full'
  get 'debit_cards/new'
  post 'debit_cards/create', to: 'debit_cards#create'
  post 'debit_cards/destroy', to: 'debit_cards#destroy'
  post 'disputes', to: 'disputes#create'
  post 'instant_transfer', to: 'debit_cards#transfer'
  get 'payouts/:id', to: 'payouts#show', as: 'payout'
  post 'webhooks/stripe', to: 'webhooks#stripe'

  resources :campaigns

  resources :stripe_accounts

  resources :charges

  resources :bank_accounts
end

app/models/stripe_account.rb
class StripeAccount < ApplicationRecord
  validates :first_name,
  presence: true, length: { minimum: 1, maximum: 40 }

  validates :last_name,
  presence: true, length: { minimum: 1, maximum: 40 }

  validates :account_type,
  presence: true, inclusion: { in: %w(individual company), message: "%{value} is not a valid account type"}

  validates :tos,
  inclusion: { in: [ true ], message: ": You must agree to the terms of service" }
end

app/controllers/stripe_accounts_controller.rb
class StripeAccountsController < ApplicationController
  before_action :authenticate_user!

  def new
    @account = StripeAccount.new
  end

  def create
    @account = StripeAccount.new(account_params)

    if @account.save
      begin
        # For readability, both account creation options are shown separately

        # First option: create an account with full account application info
        if params[:full_account]
          stripe_account = Stripe::Account.create(
            managed: true,
            legal_entity: {
              first_name: account_params[:first_name].capitalize,
              last_name: account_params[:last_name].capitalize,
              type: account_params[:account_type],
              dob: {
                day: account_params[:dob_day],
                month: account_params[:dob_month],
                year: account_params[:dob_year]
              },
              address: {
                line1: account_params[:address_line1],
                city: account_params[:address_city],
                state: account_params[:address_state],
                postal_code: account_params[:address_postal]
              },
              ssn_last_4: account_params[:ssn_last_4]
            },
            tos_acceptance: {
              date: Time.now.to_i,
              ip: request.remote_ip
            }
          )

        # Second option: create an account with incremental info
        else
          stripe_account = Stripe::Account.create(
            managed: true,
            legal_entity: {
              first_name: account_params[:first_name].capitalize,
              last_name: account_params[:last_name].capitalize,
              type: account_params[:account_type],
              dob: {
                day: account_params[:dob_day],
                month: account_params[:dob_month],
                year: account_params[:dob_year]
              }
            },
            tos_acceptance: {
              date: Time.now.to_i,
              ip: request.remote_ip
            }
          )
        end

      # If this is a business, update with these values
      if account_params[:account_type].eql?('company')
        stripe_account.legal_entity.business_name = account_params[:business_name]
        stripe_account.legal_entity.business_tax_id = account_params[:business_tax_id]
        stripe_account.save
      end

      # Save the account ID for this user for later
      @account.acct_id = stripe_account.id
      @account.save
      current_user.stripe_account = stripe_account.id

      if current_user.save
        flash[:success] = "Your account has been created!
          Next, add a bank account where you'd like to receive transfers below."
        redirect_to new_bank_account_path
      else
        handle_error("Sorry, we weren't able to create this account.", 'new')
      end

      # Handle exceptions from Stripe
      rescue Stripe::StripeError => e
        handle_error(e.message, 'new')

      # Handle any other exceptions
      rescue => e
        handle_error(e.message, 'new')
      end
    else
      @full_account = true if params[:full_account]
      handle_error(@account.errors.full_messages)
    end
  end

  def edit
    # Check for a valid account ID
    unless params[:id] && params[:id].eql?(current_user.stripe_account)
      flash[:error] = "No Stripe account specified"
      redirect_to dashboard_path and return
    end

    # Retrieve the Stripe account to find fields needed
    @stripe_account = Stripe::Account.retrieve(params[:id])

    # Retrieve the local account details
    @account = StripeAccount.find_by(acct_id: params[:id])

    if @stripe_account.verification.fields_needed.empty?
      flash[:success] = "Your information is all up to date."
      redirect_to dashboard_path and return
    end
  end

  # Custom action for full account info collection
  def full
    @account = StripeAccount.new
    @full_account = true
  end

  def update
    # Check for an existing Stripe account
    unless current_user.stripe_account
      redirect_to new_stripe_account_path and return
    end

    begin
      # Retrieve the Stripe account
      @stripe_account = Stripe::Account.retrieve(current_user.stripe_account)

      @account = StripeAccount.new(account_params)


      # Reject empty values
      account_params.each do |key, value|
        if value.empty?
          flash.now[:alert] = "Please complete all fields."
          render 'edit' and return
        end
      end

      # Iterate through each field needed
      @stripe_account.verification.fields_needed.each do |field|

        # Update each needed attribute
        case field
        when 'legal_entity.address.city'
          @stripe_account.legal_entity.address.city = account_params[:address_city]
        when 'legal_entity.address.line1'
          @stripe_account.legal_entity.address.line1 = account_params[:address_line1]
        when 'legal_entity.address.postal_code'
          @stripe_account.legal_entity.address.postal_code = account_params[:address_postal]
        when 'legal_entity.address.state'
          @stripe_account.legal_entity.address.state = account_params[:address_state]
        when 'legal_entity.dob.day'
          @stripe_account.legal_entity.dob.day = account_params[:dob_day]
        when 'legal_entity.dob.month'
          @stripe_account.legal_entity.dob.month = account_params[:dob_month]
        when 'legal_entity.dob.year'
          @stripe_account.legal_entity.dob.year = account_params[:dob_year]
        when 'legal_entity.first_name'
          @stripe_account.legal_entity.first_name = account_params[:first_name]
        when 'legal_entity.last_name'
          @stripe_account.legal_entity.last_name = account_params[:last_name]
        when 'legal_entity.ssn_last_4'
          @stripe_account.legal_entity.ssn_last_4 = account_params[:ssn_last_4]
        when 'legal_entity.type'
          @stripe_account.legal_entity.type = account_params[:type]
        when 'legal_entity.personal_id_number'
          @stripe_account.legal_entity.personal_id_number = account_params[:personal_id_number]
        when 'legal_entity.verification.document'
          @stripe_account.legal_entity.verification.document = account_params[:verification_document]
        when 'legal_entity.business_name'
          @stripe_account.legal_entity.business_name = account_params[:business_name]
        when 'legal_entity.business_tax_id'
          @stripe_account.legal_entity.business_tax_id = account_params[:business_tax_id]
        end
      end

      @stripe_account.save
      flash[:success] = "Thanks! Your account has been updated."
      redirect_to dashboard_path and return

    # Handle exceptions from Stripe
    rescue Stripe::StripeError => e
      handle_error(e.message, 'edit')

    # Handle any other exceptions
    rescue => e
      handle_error(e.message, 'edit')
    end
  end

  private
    def account_params
      params.require(:stripe_account).permit(
        :first_name, :last_name, :account_type, :dob_month, :dob_day, :dob_year, :tos,
        :ssn_last_4, :address_line1, :address_city, :address_state, :address_postal, :business_name,
        :business_tax_id, :full_account, :personal_id_number, :verification_document
      )
    end
end

app/helpers/stripe_accounts_helper.rb
module StripeAccountsHelper
  def states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/views/stripe_accounts/_account_form.html.erb
<div class="panel panel-default topspace">
  <div class="panel-body">
    <%= form_for @account do | f | %>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <%= f.label :account_type, "Account Type" %>
            <%= f.select(:account_type, options_for_select([["Individual","individual"], ["Company","company"]], @account[:account_type]), {}, { class: "form-control input-lg" }) %>
          </div>
        </div>
      </div>
      <div class="business-row <%= 'hidden' unless @account.business_name.present? %>">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :business_name, "Business name (as it appears to the IRS)" %>
              <%= f.text_field :business_name, class: "form-control input-lg", placeholder: "My Business LLC" %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :business_tax_id, "Business tax ID/EIN" %>
              <%= f.text_field :business_tax_id, class: "form-control input-lg", placeholder: "27-0000000" %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :first_name, "First Name" %>
            <%= f.text_field :first_name, class: "form-control input-lg", placeholder: "Jane" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :last_name, "Last Name" %>
            <%= f.text_field :last_name, class: "form-control input-lg", placeholder: "Doe" %>
          </div>
        </div>
      </div>
      <% if @full_account %>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :ssn_last_4, "Last 4 digits of your SSN" %>
              <%= f.text_field :ssn_last_4, class: "form-control input-lg", placeholder: "6789" %>
            </div>
          </div>
        </div>
        <%= hidden_field_tag :full_account, value: "true" %>
      <% end %>
      <hr>
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :dob_month, "DOB Month" %>
            <%= f.select(:dob_month, options_for_select([["January", "1"],["February", "2"],["March", "3"],["April", "4"],["May", "5"],["June", "6"],["July", "7"],["August", "8"],["September", "9"],["October", "10"],["November", "11"],["December", "12"]], @account[:dob_month]), {}, { class: "form-control input-lg" }) %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :dob_day, "DOB Day" %>
            <%= f.select(:dob_day, options_for_select((1..31).each{|n| [n, n]}, @account[:dob_day]), {}, { class: "form-control input-lg" }) %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :dob_year, "DOB Year" %>
            <%= f.select(:dob_year, options_for_select((1912..2016).each{|n| [n, n]}, @account[:dob_year]), {}, { class: "form-control input-lg" }) %>
          </div>
        </div>
      </div>
      <hr>
      <% if @full_account %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :address_line1, "Street address" %>
              <%= f.text_field :address_line1, class: "form-control input-lg", placeholder: "185 Berry St" %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :address_city, "City" %>
              <%= f.text_field :address_city, class: "form-control input-lg", placeholder: "San Francisco" %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :address_state, "State" %>
              <%= f.select(:address_state, options_for_select(states, @account[:address_state]), {}, { class: "form-control input-lg" }) %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :address_postal, "Zip" %>
              <%= f.text_field :address_postal, class: "form-control input-lg", placeholder: "90210" %>
            </div>
          </div>
        </div>
        <hr>
      <% end %>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <%= f.check_box :tos %>
            <%= f.label :tos do %>
              I agree to the  <%= link_to "terms of service", terms_path %>.
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <%= f.button "Create Account", class: "btn btn-primary btn-lg btn-block btn-custom", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Creating account..."} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script>
  $(function(){
    $('#stripe_account_account_type').change(function(){
      if($('#stripe_account_account_type').val() == 'company'){
          $('.business-row').removeClass('hidden'); 
        } else {
          $('.business-row').addClass('hidden'); 
        } 
    });
  });
</script>

app/views/stripe_accounts/_identity_verification_form.html.erb
<div class="panel panel-default topspace-lg">
  <div class="panel-body">
    <%= form_for @account, url: stripe_account_path(@stripe_account.id), html: { method: "patch" }  do | f | %>
      <% if @stripe_account.verification.fields_needed.find { |e| /address/ =~ e } %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :address_line1, "Street address" %>
              <%= f.text_field :address_line1, class: "form-control input-lg", placeholder: "185 Berry St" %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :address_city, "City" %>
              <%= f.text_field :address_city, class: "form-control input-lg", placeholder: "San Francisco" %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :address_state, "State" %>
              <%= f.select(:address_state, options_for_select(states, @account[:address_state]), {}, { class: "form-control input-lg" }) %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label>Zip code</label>
              <%= f.label :address_postal, "Zip" %>
              <%= f.text_field :address_postal, class: "form-control input-lg", placeholder: "90210" %>
            </div>
          </div>
        </div>
        <hr>
      <% end %>
      <% if @stripe_account.verification.fields_needed.include?('legal_entity.type') %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :account_type, "Account Type" %>
              <%= f.select(:account_type, options_for_select([["Individual","individual"], ["Company","company"]], @account[:account_type]), {}, { class: "form-control input-lg" }) %>
            </div>
          </div>
        </div>
      <% end %>
      <% if @stripe_account.verification.fields_needed.find { |e| /name/ =~ e } %>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :first_name, "First Name" %>
              <%= f.text_field :first_name, class: "form-control input-lg", placeholder: "Jane" %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :last_name, "Last Name" %>
              <%= f.text_field :last_name, class: "form-control input-lg", placeholder: "Doe" %>
            </div>
          </div>
        </div>
      <% end %>
      <% if @stripe_account.verification.fields_needed.find { |e| /dob/ =~ e } %>
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :dob_month, "DOB Month" %>
              <%= f.select(:dob_month, options_for_select([["January", "1"],["February", "2"],["March", "3"],["April", "4"],["May", "5"],["June", "6"],["July", "7"],["August", "8"],["September", "9"],["October", "10"],["November", "11"],["December", "12"]], @account[:dob_month]), {}, { class: "form-control input-lg" }) %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :dob_day, "DOB Day" %>
              <%= f.select(:dob_day, options_for_select((1..31).each{|n| [n, n]}, @account[:dob_day]), {}, { class: "form-control input-lg" }) %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :dob_year, "DOB Year" %>
              <%= f.select(:dob_year, options_for_select((1912..2016).each{|n| [n, n]}, @account[:dob_year]), {}, { class: "form-control input-lg" }) %>
            </div>
          </div>
        </div>
        <hr>
      <% end %>
      <% if @stripe_account.verification.fields_needed.include?('legal_entity.business_name') %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :business_name, "Business name (as it appears to the IRS)" %>
              <%= f.text_field :business_name, class: "form-control input-lg", placeholder: "My Business LLC" %>
            </div>
          </div>
        </div>
      <% end %>
      <% if @stripe_account.verification.fields_needed.include?('legal_entity.business_tax_id') %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :business_tax_id, "Business tax ID/EIN" %>
              <%= f.text_field :business_tax_id, class: "form-control input-lg", placeholder: "27-0000000" %>
            </div>
          </div>
        </div>
      <% end %>
      <% if @stripe_account.verification.fields_needed.include?('legal_entity.ssn_last_4') %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :ssn_last_4, "Last 4 digits of your SSN" %>
              <%= f.text_field :ssn_last_4, class: "form-control input-lg", placeholder: "6789" %>
            </div>
          </div>
        </div>
      <% end %>
      <% if @stripe_account.verification.fields_needed.include?('legal_entity.personal_id_number') %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <label>Full social security number (used to verify your identity)</label>
              <input type="text" id="personal_id_number" class="form-control input-lg" placeholder="123-45-6789" required>
              <span class="help-block">Never stored, only used to verify your identity.</span>
            </div>
          </div>
        </div>
      <% end %>
      <% if @stripe_account.verification.fields_needed.include?('legal_entity.verification.document') %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <label>Upload a photo ID</label>
              <input type="file" id="file_upload" name="file" required>
              <span class="help-block">We need a picture of your government-issued ID to verify your identity.</span>
            </div>
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <button type="submit" class="btn btn-lg btn-block btn-primary btn-custom submit">Submit your information</button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  Stripe.setPublishableKey("<%= ENV['PUBLISHABLE_KEY'] %>");

  $(function() {
    var $form = $('form');

    // If a personal ID number is requested, tokenize it
    if ($('#personal_id_number').length){
      $form.submit(function(event) {
        // Disable the submit button to prevent repeated clicks:
        $form.find('.submit').prop('disabled', true).html("<i class='fa fa-spinner fa-spin'></i> Submitting your information...");
        // Create the token using Stripe.js
        Stripe.piiData.createToken({
          personal_id_number: $('#personal_id_number').val()
        }, stripeResponseHandler);
        return false;
      });
    }
    function stripeResponseHandler(status, response) {
      // Grab the form:
      var $form = $('form');

      if (response.error) { // Problem!
        // Let the user know there was a problem
        $form.append("<div class='alert alert-danger'>"+response.error.message+"</div>");
        $form.find('.submit').prop('disabled', false); // Re-enable submission

      } else { // Token created!
        $form.find('.submit').html("<i class='fa fa-check'></i> Information submitted");

        // Get the token ID:
        var token = response.id;

        // Insert the token into the form so it gets submitted to the server:
        $form.append($('<input type="hidden" name="stripe_account[personal_id_number]" />').val(token));

        // Submit the form:
        $form.get(0).submit();
      }
    }
    // If an identity document is requested, upload it
    if ($('#file_upload').length){
      $form.submit(function(event) {
        // Prevent the form submission
        event.preventDefault();

        // Disable the submit button to prevent repeated clicks:
        $form.find('.submit').prop('disabled', true).html("<i class='fa fa-spinner fa-spin'></i> Submitting your information...");
        // Remove any existing errors
        $form.find('.alert-danger').remove();

        var data = new FormData();
        data.append('file', $('#file_upload')[0].files[0]);
        data.append('purpose', 'identity_document');

        $.ajax({
          url: 'https://uploads.stripe.com/v1/files',
          data: data,
          headers: {
            'Authorization': 'Bearer ' + "<%= ENV['PUBLISHABLE_KEY'] %>"
          },
          cache: false,
          contentType: false,
          processData: false,
          type: 'POST',
        })
        .done(function(response) {
          // Insert the token into the form so it gets submitted to the server:
          $form.append($('<input type="hidden" name="stripe_account[verification_document]" />').val(response.id));
          // Submit the form:
          $form.get(0).submit();
        })
        .fail(function(response) {
          $form.append("<div class='alert alert-danger'>"+response.responseJSON.error.message+"</div>");
          $form.find('.submit').prop('disabled', false).text('Submit your information'); // Re-enable submission
        });
      });
    }
  });
</script>

app/views/stripe_accounts/edit.html.erb
<%= content_for :page_title, 'Fundraising Marketplace | Submit your account info' %>
<div class="container">
  <div class="row topspace-lg">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">
        Update your account
      </h1>
      <div>
        <%= render 'layouts/messages' %>
        <%= render 'identity_verification_form' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <a href="https://stripe.com/docs/connect/testing#identity-verification" target="_blank">Stripe Connect test numbers</a>
    </div>
  </div>
</div>

app/views/stripe_accounts/full.html.erb
<%= content_for :page_title, 'Fundraising Marketplace | Submit your info' %>
<div class="container">
  <div class="row topspace-lg">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Submit your account application</h1>
      <div>
        <%= render 'layouts/messages' %>
        <%= render 'account_form' %>
        <p class="text-center">
          <%= link_to 'Collect info incrementally', new_stripe_account_path %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/stripe_accounts/new.html.erb
<%= content_for :page_title, 'Fundraising Marketplace | Get Paid' %>
<div class="container">
  <div class="row topspace-lg">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Get Paid</h1>
      <div>
        <%= render 'layouts/messages' %>
        <%= render 'account_form' %>
      </div>
    </div>
  </div>
</div>