config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root to: "campaigns#home"
  get 'dashboard', to: 'campaigns#dashboard'
  get 'pricing', to: 'pages#pricing'
  get 'terms', to: 'pages#terms'
  get 'stripe_accounts/full', to: 'stripe_accounts#full'
  get 'debit_cards/new'
  post 'debit_cards/create', to: 'debit_cards#create'
  post 'debit_cards/destroy', to: 'debit_cards#destroy'
  post 'disputes', to: 'disputes#create'
  post 'instant_transfer', to: 'debit_cards#transfer'
  get 'payouts/:id', to: 'payouts#show', as: 'payout'
  post 'webhooks/stripe', to: 'webhooks#stripe'

  resources :campaigns

  resources :stripe_accounts

  resources :charges

  resources :bank_accounts
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user

  validates :title,
  presence: true, length: { minimum: 5, maximum: 100 }

  validates :goal, 
  presence: true, numericality: { greater_than: 20, less_than: 1000000 }

  validates :description,
  presence: true, length: { minimum: 10, maximum: 5000 }
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!, except: [:home, :show]
  include CampaignsHelper

  def home
    # Retrieve all active campaigns
    @campaigns = Campaign.where(active: true).order(created_at: :desc).page params[:page]
  end

  def new
    # Redirect if no existing Stripe account
    unless current_user.stripe_account
      redirect_to new_stripe_account_path and return
    end

    # Populate random campaign info
    random_campaign

    # Create a new campaign object
    @campaign = Campaign.new
  end

  def create
    # Create a campaign for the user
    @campaign = current_user.campaigns.new(campaign_params)

    # Redirect to the campaign page once created
    if @campaign.save
      flash[:notice] = "Your campaign has been created!"
      redirect_to @campaign
    else
      handle_error(@campaign.errors.full_messages, 'new')
    end
  end

  def show
    # Retrieve a campaign
    @campaign = Campaign.find(params[:id])

    # List all charges for a given campaign
    @charges = Charge.where(campaign_id: @campaign.id, amount_refunded: nil).order(created_at: :desc)
  end

  def dashboard
    # List campaigns for the current user
    @campaigns = current_user.campaigns.order(created_at: :desc)

    # Redirect if there's not a Stripe account for this user yet
    unless current_user.stripe_account
      flash[:success] = "Create an account to get started."
      redirect_to new_stripe_account_path and return
    end

    # Retrieve charges, transfers, balance transactions, & balance from Stripe
    begin
      @stripe_account = Stripe::Account.retrieve(current_user.stripe_account)

      # Last 100 charges
      @payments = Stripe::Charge.list(
        {
          limit: 100,
          expand: ['data.source_transfer.source_transaction.dispute', 'data.application_fee'],
          source: {object: 'all'}
        },
        { stripe_account: current_user.stripe_account }
      )

      # Last 100 payouts from the managed account to their bank account
      @payouts = Stripe::Payout.list(
        {
          limit: 100,
          expand: ['data.destination']
        },
        { stripe_account: current_user.stripe_account }
      )

      # Retrieve available and pending balance for an account
      @balance = Stripe::Balance.retrieve(stripe_account: current_user.stripe_account)
      @balance_available = @balance.available.first.amount + @balance.pending.first.amount

      # Retrieve transactions with an available_on date in the future
      # For a large platform, it's generally preferrable to handle these async
      transactions = Stripe::BalanceTransaction.all(
        {
          limit: 100,
          available_on: {gte: Time.now.to_i}
        },
        { stripe_account: current_user.stripe_account }
      )

      # Iterate through transactions and sum values for each available_on date
      # For a production app, you'll probably want to store and query these locally instead
      balances = Hash.new
      transactions.auto_paging_each do |txn|
        if balances.key?(txn.available_on)
          balances[txn.available_on] += txn.net
        else
          balances[txn.available_on] = txn.net
        end
      end

      # Sort the results
      @transactions = balances.sort_by {|date,net| date}

      # Check for a debit card external account and determine amount for payout
      @debit_card = @stripe_account.external_accounts.find { |c| c.object == "card"}
      @instant_amt = @balance_available*0.97
      @instant_fee = @balance_available*0.03

    # Handle Stripe exceptions
    rescue Stripe::StripeError => e
      flash[:error] = e.message
      redirect_to root_path

    # Handle other exceptions
    rescue => e
      flash[:error] = e.message
      redirect_to root_path
    end
  end

  def edit
    # Retrieve the campaign
    @campaign = Campaign.find(params[:id])
  end

  def update
    # Retrieve the campaign
    @campaign = Campaign.find(params[:id])

    # Redirect to view campaign
    if @campaign.update_attributes(campaign_params)
      flash[:notice] = "Your campaign has been updated!"
      redirect_to @campaign
    else
      handle_error(@campaign.errors.full_messages, 'edit')
    end
  end

  def destroy
    # Retrieve the campaign
    campaign = Campaign.find(params[:id])

    # Respond with deletion status
    if campaign.update_attributes(active: false)
      flash[:notice] = "Your campaign has been deleted."
      redirect_to dashboard_path
    else
      flash[:error] = "We weren't able to delete this campaign."
      redirect_to dashboard_path
    end
  end

  private
    def campaign_params
      params.require(:campaign).permit(:title, :description, :goal, :subscription, :image)
    end

    def random_campaign
      data = campaign_data.sample
      @campaign_title = data[:title]
      @campaign_description = data[:description]
      @campaign_image = data[:image]
      @goal = amounts.sample
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def campaign_data
    [
      { 
        title: "Donate to my college loan relief fund!",
        description: "After college I'm left with some fairly large student loan debt! If you'd like to contribute to help me pay this off, please consider making a donation!",
        image: "money"
      },
      { 
        title: "Help send my dog to surf school",
        description: "My dog, Russ, wants to learn to surf. Please donate to help us pay for it so he can shred sick waves!",
        image: "beach"
      },
      { 
        title: "Help us adopt a puppy with your name!",
        description: "We'd like to adopt a puppy, but need money for the adoption fees and vet bills. In return for your donation, we'll name our dog after you!",
        image: "puppy"
      },
      { 
        title: "Send me on a trip around the world",
        description: "I just want to check out the world and it's expensive. Help me buy my ticket and in return I will send you a post card.",
        image: "travel"
      },
      { 
        title: "Make a donation to our pool fund",
        description: "It's hot out hurr in Phoenix! Help us put in a swimming pool so we can go outside and float around.",
        image: "money"
      },
      { 
        title: "Send me on a ski trip!",
        description: "I want to shred the gnar pow in Aspen with my frands. Will you help fund my gnarly sesh?",
        image: "snow"
      },
      { 
        title: "Help me buy a new snowboard",
        description: "My current snowboard is ugggly and I need a new board to properly shred the gnar and keep it steezy. Please halp!",
        image: "snow"
      },
      { 
        title: "Fund our cabin rental",
        description: "We need money to fund our cabin rental while we take a family vacation. If you don't donate, we'll be forced to sleep in our van, no biggie.",
        image: "snow"
      },
      { 
        title: "Help me pay for my ski lessons!",
        description: "I am turrible at skiing and need to ride the black diamonds to impress my frands. Donate pleaaaase!",
        image: "snow"
      },
      { 
        title: "Help me start a ski school",
        description: "My greatest skill is skiing and my dream is to spend my life in the freshies. I want to bring this joy to others and just need some money to do it. If you donate, I'll give 1% off a lesson!",
        image: "snow"
      },
      { 
        title: "Give me money for lottery tickets",
        description: "I have a PROVEN METHOD to win the lottery and I just need your investments to help me pay for it. In return, I will share part of the proceeds with you.",
        image: "money"
      },
      { 
        title: "Help me fund my Lacroix habit",
        description: "Listen, I'm putting down 1 or 2 cases of Lacroix each day. It's delicious! No additives! But it's costing me bigly. Will you help me pay for it?",
        image: "money"
      },
      { 
        title: "I need money to fly first class",
        description: "I'm flying to Duluth next month and want to go in style. That's right: I'm talking first class. With the celebrities and CEOs. Thanks for your donations.",
        image: "travel"
      },
      { 
        title: "Pay for my ticket home from Las Vegas",
        description: "It's likely that after my Vegas trip next week I'll need some assistance paying for the flight home. Thanks in advance.",
        image: "travel"
      },
      { 
        title: "Pay for my surf school",
        description: "I'm quitting my job and starting a surf school! I just need your money to make that happen. Please donate?",
        image: "beach"
      },
      { 
        title: "Need a new beach umbrella",
        description: "My last beach umbrella blew away :(. Please help me pay for a new one so I don't get buuurned.",
        image: "beach"
      },
      { 
        title: "Help fund our honeymoon to Fiji",
        description: "We're heading to Fiji for a honeymoon and need money to get there! If you donate, we'll bring you back some sand or something.",
        image: "beach"
      },
      { 
        title: "Help me start a startup",
        description: "I'm quitting my day job and starting a tech startup with a brilliant idea: flying squirrel rental as a service. Please invest!",
        image: "desk"
      },
      { 
        title: "Help launch my startup",
        description: "We're launching the world's next big startup: dishwashing as a service. For just $200 a month, we'll come to your house and wash your dishes for you! Donate now and get a month free!",
        image: "desk"
      },
      { 
        title: "Help me start a tech company",
        description: "Someone said that machine learning is all the rage, so I'm starting a startup where people can learn machine learning from machines via machine learning. It's brilliant!",
        image: "desk"
      },
      { 
        title: "Pay for my next notebook",
        description: "Look folks, I've got lots of great ideas and notes filling up my moleskines... and these things aren't cheap! Please help me pay for the next one. Thaaaaanks.",
        image: "desk"
      },
      { 
        title: "Invest in my next big idea",
        description: "You may remember me as the guy that started America's hottest chainsaw rental app, chainsawrr. Well I've got something big coming soon and need your investment! Get in now!",
        image: "desk"
      },
      { 
        title: "Help offset the cost of dog training",
        description: "My dog is a huge jerk and needs some training. Please donate and help me pay for this thing so she can get the help she neeeeeds!",
        image: "puppy"
      },
      { 
        title: "Fund our trip to Greece",
        description: "We're going to Greece for a few days because it's beautiful and we like Gyros. Please help fund our Gyro habit!",
        image: "ocean"
      },
      { 
        title: "Get me a photography lesson",
        description: "I want to take photography lessons because right now all my pictures are shaky and look like junk. I just need some money to make this happen! In return, I'll take your picture.",
        image: "ocean"
      },
      { 
        title: "Trip to California",
        description: "I've always wanted to go to California because it's the best state in the country. Pls halp me afford it by giving me some money!",
        image: "ocean"
      },
      { 
        title: "Hiking trip in San Diego",
        description: "We're going hiking in America's finest city and need some new boots. Please don't make me wear these old boots! Donate now and I'll be forever grateful.",
        image: "ocean"
      },
      { 
        title: "Drive up the coast",
        description: "I'm going to drive up the coast and need help with the cost of gas for my Humvee!",
        image: "ocean"
      },
      { 
        title: "Vacation to San Diego",
        description: "We're taking the kids to San Diego and saving our pennies... but not getting there fast enough! Please make a donation or we'll never talk to you again. Thanks.",
        image: "ocean"
      },
      { 
        title: "Help us see the full house house",
        description: "Remember Full House? We're big Danny Tanner fans and want to see the place where it all went down: San Francisco. Donate now to help us fund the trip!",
        image: "sf"
      },
      { 
        title: "Buy me a slice of artisian toast",
        description: "Living in San Francisco means I only eat the finest toast. Please help me buy a slice.",
        image: "sf"
      },
      { 
        title: "Help me pay my rent!",
        description: "My rent increased and I need some help paying for it! Please donate or let me know if it's okay for me to crash on your couch for a month or two.",
        image: "sf"
      },
      { 
        title: "Give us a wedding gift!",
        description: "We're getting married and need money to pay for the ceremony! If you care at all about either of us, please give generously.",
        image: "wedding"
      },
      { 
        title: "Help pay for our wedding photography",
        description: "We got a sweet wedding photographer to agree to take our photos and need help paying for it. Otherwise, we'll probably just take photos ourselves with our iPhones. :(",
        image: "wedding"
      }
    ]
  end

  def amounts
    [
      "100.00",
      "125.00",
      "150.00",
      "200.00",
      "250.00",
      "300.00",
      "350.00",
      "400.00",
      "450.00",
      "500.00",
      "600.00",
      "700.00",
      "750.00",
      "900.00",
      "1000.00",
      "1500.00",
      "2000.00",
      "2500.00",
      "3000.00",
      "3500.00",
      "4000.00",
      "5000.00",
      "7500.00",
      "10000.00"
    ]
  end
end

app/views/campaigns/_campaigns.html.erb
<% @campaigns.each_slice(3) do | campaigns | %>
  <div class="row">
    <% campaigns.each do |campaign| %>
      <div class="col-md-4">
        <div class="panel panel-default campaign">
          <%= link_to campaign_path(campaign) do %>
            <div class="panel-body">
              <%= image_tag("#{campaign.image}_sm.jpg") %>
              <div class="body-padding">
                <h4 class="text-center"><%= link_to campaign.title.titleize, campaign_path(campaign) %></a></h4>
                <p class="goal text-center">
                  <% if campaign.raised %>
                     <span class="raised"><%= number_to_currency(campaign.raised/100, precision: 0) %></span> raised so far of <strong><%= number_to_currency(campaign.goal, precision: 0) %> goal</strong>
                  <% else %>
                    <strong><%= number_to_currency(campaign.goal, precision: 0) %> goal</strong>
                  <% end %>
                </p>
                <p>
                  <%= simple_format(truncate(campaign.description, length: 90)) %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/campaigns/_charges.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th>Payment ID</th>
          <th>Amount</th>
          <th>Net</th>
          <th>Created</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @payments.each do |payment| %>
          <% if payment.source_transfer.source_transaction.present? %>
            <tr>
              <td>
                <% if payment.source_transfer.source_transaction.source.object.eql?('card') %>
                  <i class="fa fa-credit-card text-muted"></i>
                <% end %>
                <%= link_to payment.source_transfer.source_transaction.id, charge_path(payment.source_transfer.source_transaction.id), class: "leftspace" %>
                <% if payment.source_transfer.source_transaction.dispute.present? %>
                  <% if payment.source_transfer.source_transaction.dispute.status.eql?('needs_response') %>
                    <span class="label label-danger leftspace">Disputed</span>
                  <% elsif payment.source_transfer.source_transaction.dispute.status.eql?('lost') %>
                    <span class="label label-default leftspace">Dispute lost</span>
                  <% elsif payment.source_transfer.source_transaction.dispute.status.eql?('won') %>
                    <span class="label label-success leftspace">Dispute won</span>
                  <% end %>
                <% end %>
              </td>
              <td><%= number_to_currency(payment.amount/100) %></td>
              <td><%= format_amount(payment.amount - payment.application_fee.amount) %></td>
              <td><%= format_date(payment.created) %></td>
              <td class="text-center">
                <% if payment.refunded %>
                  <span class="text-danger">
                    <span class="fa fa-undo"></span> Refunded
                  </span>
                <% else %>
                  <%= link_to "Refund", charge_path(payment.source_transfer.source_transaction.id), method: :delete, data: { confirm: "Are you sure you want to refund this charge?", disable_with: "<i class='fa fa-spinner fa-spin'></i> Refunding charge..." }, class: "btn btn-sm btn-block btn-custom btn-danger" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/campaigns/_checkoutform.html.erb
<div class="panel panel-default panel-payment">
  <div class="panel-body">
    <form action="/charges" method="POST" id="checkout_form">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Cardholder Name</label>
            <input class="form-control input-lg" id="name" name="name" type="text" data-stripe="name" placeholder="Jimmy Dean">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Donation amount</label>
            <input class="form-control input-lg" id="amount" name="amount" type="text" placeholder="$20.00">
          </div>
        </div>
      </div>
      <input type="hidden" id="stripeToken" name="stripeToken" />
      <input type="hidden" name="campaign" value="<%= @campaign.id %>">
      <button id="checkoutBtn" class="btn btn-lg btn-block btn-custom btn-purple">Make a donation</button>
    </form>
  </div>
</div>
<p class="text-center topspace">
  <a href="?">Use Stripe Elements</a>
</p>

app/views/campaigns/_transfers.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th>Transfer ID</th>
          <th>Destination</th>
          <th>Amount</th>
          <th>Deposit date</th>
        </tr>
      </thead>
      <tbody>
        <% @payouts.each do |payout| %>
          <tr>
            <td>
              <% if payout.type.eql?('bank_account') %>
                <i class="fa fa-bank text-muted"></i>
                <%= link_to payout.id, payout_path(payout.id), class: "leftspace" %>
              <% else %>
                <i class="fa fa-credit-card text-muted"></i>
                <span class="leftspace"><%= payout.id %></span>
              <% end %>
            </td>
            <td>
              <% if payout.type.eql?('bank_account') %>
                <%= payout.destination.bank_name %> ending in <%= payout.destination.last4 %>
              <% elsif payout.type.eql?('card') %>
                <%= payout.destination.brand %> ending in <%= payout.destination.last4 %>
              <% end %>
            </td>
            <td><%= format_amount(payout.amount) %></td>
            <td><%= format_date(payout.arrival_date) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/campaigns/_verification.html.erb
<% if @stripe_account.verification.fields_needed %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-warning text-center shadow-sm">
        <h4>
          We need some information to continue processing donations for you. 
        </h4>
        <p>
          <%= link_to "Update your information", edit_stripe_account_path(@stripe_account.id), class: "btn btn-lg btn-warning btn-custom" %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/campaigns/dashboard.html.erb
<%= content_for :page_title, 'Fundraising Marketplace | Dashboard' %>
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center topspace">
      <%= render 'layouts/messages' %>
    </div>
  </div>
  <% unless @stripe_account.verification.fields_needed.empty? %>
    <%= render 'verification' %>
  <% end %>
  <h2 class="page-header"><i class="fa fa-line-chart purple"></i>  My Campaigns</h2>
  <% unless @campaigns.empty? %>
    <%= render 'campaigns' %>
  <% else %>
    <%= link_to "Create your first fundraising campaign to get started", new_campaign_path %>.
  <% end %>
  <h2 class="page-header">
    <i class="fa fa-dollar purple"></i>  Donations
    <br><small><span class="raised"><%= format_amount(@balance_available) %></span> pending</small>
  </h2>
  <div class="panel panel-default">
    <div class="panel-body">
      <% unless @payments.data.empty? %>
        <%= render 'charges' %>
        <% if @balance_available > 0 %>
          <div class="topspace text-center">
            <h3>Want your funds immediately?</h3>
            <p>
              For an extra 3% fee, we'll create an instant transfer to your debit card.
            </p>
            <% if @debit_card %>
              <%= button_to "Get this transfer instantly", instant_transfer_path, data: { confirm: "Instant payout #{format_amount(@instant_amt)} to your #{@debit_card.brand} debit card ending in #{@debit_card.last4}?", disable_with: "Transferring funds..." }, method: :post, params: { amount: @instant_amt.round, fee: @instant_fee.round, destination: @debit_card.id }, class: "btn btn-success btn-lg btn-custom" %>
            <% else %>
              <%= link_to "Add a debit card", debit_cards_new_path, class: "btn btn-lg btn-success btn-custom" %>
            <% end %>
          </div>
        <% end %>
      <% else %>
        No donations yet.
      <% end %>
    </div>
  </div>
  <h2 class="page-header"><i class="fa fa-bank purple"></i> Payouts</h2>
  <div class="panel panel-default">
    <div class="panel-body">
      <% unless @payouts.data.empty? %>
        <%= render 'transfers' %>
      <% else %>
        No payouts yet.
      <% end %>
    </div>
  </div>
</div>

app/views/campaigns/show.html.erb
<%= content_for :page_title, "#{@campaign.title.titleize} | Fundraising Marketplace" %>
<% content_for(:header) do %>
  <% if params[:checkout].present? %>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <script>
      $(function() {
        var handler = StripeCheckout.configure({
          key: '<%= ENV['PUBLISHABLE_KEY'] %>',
          image: 'https://stripe.com/img/documentation/checkout/marketplace.png',
          locale: 'auto',
          token: function(token) {
            $("#stripeToken").val(token.id);
            $("#checkout_form").submit();
          }
        });

        document.getElementById('checkoutBtn').addEventListener('click', function(e) {
          // Clear any errors
          $('#amount').parent('.form-group').removeClass('has-error');

          // Check for a valid amount
          if ($('#amount').val() == ''){
            $('#amount').parent('.form-group').addClass('has-error');
            e.preventDefault();
            return false;
          }
          else {
            // Set the donation amount
            var amount = $("#amount").val().replace('$','') * 100;
            var displayAmount = parseFloat(Math.floor($("#amount").val() * 100) / 100).toFixed(2);
          }

          // Open Checkout with further options:
          handler.open({
            name: 'Fundraising Marketplace',
            description: 'Donation',
            zipCode: true,
            amount: amount
          });
          e.preventDefault();
        });

        // Close Checkout on page navigation:
        window.addEventListener('popstate', function() {
          handler.close();
        });
      });
    </script>
  <% else %>
    <script src="https://js.stripe.com/v3/"></script>
    <script>
      $(function(){
        var stripe = Stripe("<%= ENV['PUBLISHABLE_KEY'] %>");

        var elements = stripe.elements();

        // Style the payment element
        var style = {
          base: {
            fontSize: "15px",
            fontFamily: '"Open Sans", sans-serif',
            fontSmoothing: 'antialiased',
            '::placeholder': {
              color: '#666',
            },
          }
        };

        // Create an instance of the card Element
        var card = elements.create('card', {style: style});

        // Add an instance of the card Element into the `card-element` <div>
        card.mount('#card-element');

        // Listen for errors
        card.addEventListener('change', function(event) {
          var displayError = document.getElementById('card-errors');
          if (event.error) {
            displayError.textContent = event.error.message;
            displayError.style.display = 'block';
          } else {
            displayError.textContent = '';
            displayError.style.display = 'none';
          }
        });

        // Create a token
        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function(event) {
          event.preventDefault();

          // Clear any error styles
          document.getElementById('amount').parentElement.classList.remove("has-error");
          document.getElementById('name').parentElement.classList.remove("has-error");

          // Validate the form isn't empty before requesting a token
          if (document.getElementById('amount').value == ''){
            document.getElementById('amount').parentElement.classList.add("has-error");
            return false;
          }
          else if (document.getElementById('name').value == ''){
            document.getElementById('name').parentElement.classList.add("has-error");
            return false;
          }

          var submit_btn = document.getElementById('submit_payment');
          var errorElement = document.getElementById('card-errors');
          submit_btn.innerHTML = "<i class='fa fa-spinner fa-spin'></i> Making donation...";
          submit_btn.className += " disabled";
          var cardDetails = {name: form.querySelector('input[name=name]').value};
          stripe.createToken(card, cardDetails).then(function(result) {
            if (result.error) {
              errorElement.textContent = result.error.message;
              errorElement.style.display = 'block';
              submit_btn.innerHTML = "Make a donation";
              submit_btn.classList.remove("disabled");
            } else {
              // Reset errors
              errorElement.textContent = '';
              errorElement.style.display = 'none';
              // Send the token to your server
              stripeTokenHandler(result.token);
            }
          });
        });

        // Submit the token
        function stripeTokenHandler(token) {
          // Insert the token ID into the form so it gets submitted to the server
          var form = document.getElementById('payment-form');
          var hiddenInput = document.createElement('input');
          hiddenInput.setAttribute('type', 'hidden');
          hiddenInput.setAttribute('name', 'stripeToken');
          hiddenInput.setAttribute('value', token.id);
          form.appendChild(hiddenInput);

          // Submit the form
          form.submit();
        }
      });
    </script>
  <% end %>
<% end %>
<div class="container campaign-content">
  <div class="row topspace-lg">
    <div class="col-md-8">
      <%= render 'layouts/messages' %>
      <% unless @campaign.active %>
        <div class="alert alert-danger">
          This campaign is no longer active.
        </div>
      <% end %>
      <div class="text-center">
        <%= image_tag("#{@campaign.image}_lg.jpg", class: "img-responsive") %>
      </div>
      <h2 class="page-header text-center purple">
        <%= @campaign.title.titleize %>
      </h2>
      <h3 class="goal text-center">
        <% if @campaign.raised %>
           <span class="raised"><%= format_amount(@campaign.raised) %></span> raised so far of <strong><%= number_to_currency(@campaign.goal, precision: 0) %> goal</strong>
        <% else %>
          <strong><%= number_to_currency(@campaign.goal) %> goal</strong>
        <% end %>
      </h3>
      <blockquote class="lato topspace-lg">
        <%= simple_format(@campaign.description) %>
      </blockquote>
      <h3 class="text-center page-header">Donations</h3>
      <% unless @campaign.raised.to_i > 0 %>
        This campaign has not received any donations yet.
      <% else %>
        <%= render 'donations' %>
      <% end %>
    </div>
    <div class="col-md-4">
      <% if @campaign.active %>
        <% if params[:checkout].present? %>
          <%= render 'checkoutform' %>
        <% else %>
          <%= render 'paymentform' %>
        <% end %>
        <div class="text-muted text-center">
          <p>
            <i class="fa fa-info-circle"></i> Hint: use a <a href="https://stripe.com/docs/testing#cards" target="_blank">Stripe test card</a> and any valid expiry.
          </p>
        </div>
      <% end %>
      <% if current_user && @campaign.user_id.eql?(current_user.id) && @campaign.active %>
        <h3 class="page-header text-center"><i class="fa fa-edit purple"></i> Your campaign</h3>
        <p>
          <%= link_to "Edit this campaign", edit_campaign_path(@campaign),
            class: "btn btn-lg btn-primary btn-custom btn-block"%>
        </p>
        <p>
          <%= link_to "Delete this campaign", campaign_path(@campaign), method: :delete, data: { confirm: "Are you sure you want to delete this campaign?" }, class: "btn btn-lg btn-block btn-custom btn-danger" %>
        </p>
      <% end %>
    </div>
  </div>
</div>